FROM alpine:3.13
RUN apk  update && apk add --no-cache \
                     curl \
	tzdata \
	unzip \
	php7 \
	php7-curl \
	php7-phar \
	php7-cli \
	php7-fpm \
	php7-mysqlnd \
	php7-mysqli \
	php7-pdo_mysql \
	php7-common \
	php7-opcache \
	php7-bcmath \
	php7-gd \
	php7-mbstring \
	php7-pdo \
	php7-pdo_pgsql \
	php7-pgsql \
	php7-json \
	php7-intl \
	php7-fileinfo \
	php7-ctype \
	php7-dom \
	php7-iconv \
	php7-simplexml \
	php7-xml \
	php7-xmlreader \
	php7-xmlwriter \
	php7-tokenizer \
	php7-session \
	php7-pecl-redis \
	php7-zip php7-xdebug php7-sqlite3 php7-pdo_sqlite openssh git
WORKDIR /opt
	